name: Build project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
      if: false
      with:
        fetch-depth: 0
        submodules: recursive
  
    - name: Install Qt
      run: |
        curl -vLo qt-installer.exe https://download.qt.io/official_releases/online_installers/qt-unified-windows-x64-online.exe
        dir
        ./qt-installer.exe --accept-licenses --accept-messages --confirm-command install qt.qt5.5152.win64_msvc2019_64 --root "${{ github.workspace }}/Qt" --email "${{ secrets.QT_INSTALLER_EMAIL }}" --pw "${{ secrets.QT_INSTALLER_PASSWORD }}"

    - name: Configure build for x86
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
    
    - name: Build project
      env:
        QT5_DIR: "${{ github.workspace }}/qtroot/Qt/5.15.2/msvc2019_64"
      run: |
        tree "${{ github.workspace }}/Qt"

        cd "${{ github.workspace }}/Qt"
        dir
        # mkdir build && cd build
        # rem cmake -G "Ninja" -DQt5_ROOT="${{ env.QT5_DIR }}" -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=Release ../src
        # rem ninja all install

    - uses: actions/upload-artifact@v3
      with:
        name: ImgToPdfConverter
        path: build/install/*
